### ISSUE TITLE
threshold value used for NYU Dataset

### ISSUE THREAD

**Issue by zzangjinsun** [imransai/Depth-Coefficients-from-Single-Image#3]
First of all, thank you for sharing your codes for great work!

I just wonder which threshold value t is used for NYUDepthV2 dataset evaluation (Tab. 1 in the paper)?

It seems that 100 is used for the KITTI dataset.

Thank you very much!

**Comment by imransai** [comment]
Hi Jinsun, We were using t = 10 for NYU dataset. And you are right, we used t = 100 for KITTI dataset.

Thanks!

**Comment by zzangjinsun** [comment]
Thank you very much!!
