### ISSUE TITLE
About normalize KITTI depth data

### ISSUE THREAD

**Issue by mzy97** [imransai/Depth-Coefficients-from-Single-Image#4]
Hi, thank you for opensource such a great work

I found in dataReader, line 146, see also link below. you use depth * 100 / 256, we know that depth / 256 can get depth in meter, why multiply 100, there might be something wrong, it should be depth / 256/ 100

https://github.com/imransai/Depth-Coefficients-4-DepthCompletion/blob/050855a1b616a60eb3af36450f2d2a7edac92f0c/Codes/dataReader.py#L144

**Comment by imransai** [comment]
Hi, I multiplied it by 100 to make to cm from m, since each of DC bin step size is 1m = 100 cm.  Note, my results were in cm, so I had to convert that to m in the final predicted output. But, if you want to keep it in m unit, that is fine too. You just need to adjust certain parts of the code.

**Comment by mzy97** [comment]
Thanks for your reply, i understand it. another question, i find the idea of depth coefficient is similar to this paper "Deep Ordinal Regression Network for Monocular Depth Estimation". but beautiful than it. is this idea inspired by it to some extent?

**Comment by mzy97** [comment]
There also a confusing point that in this line
https://github.com/imransai/Depth-Coefficients-4-DepthCompletion/blob/050855a1b616a60eb3af36450f2d2a7edac92f0c/Codes/dataReader.py#L69

why add another two channels, what these two channels for?

**Comment by imransai** [comment]
Good point. Remember, the DC comprised of three bins, so if I start my depth range from 0.5-80.5 m, I would need that boundary bins to comprise my neighboring bins. So in total there are 82 bins to cover a range of 0.5-80.5m.  I guess you can keep it to 80 bins also, depending on how much depth range you want to cover.

I am aware of that paper, but idea is not motivated by that paper. We wanted to describe depth as uncertainty measure/probability measure whereas they mostly devise a new loss function (ordinal regression loss) to predict depth.

**Comment by mzy97** [comment]
thanks alot!
